Repository dotrachit/summit, pull requests merged in 2020-11, with the labels that each got.

#26 Fixed MixedContent error
  public/index.html
Labels: bug

#28 Fixed output header condition
  src/components/summarizer.js
Labels: bug, frontend

#30 fixed the check original blog button
  src/components/summarizer.js
Labels: bug, frontend

#34 Fixed the CORS error
  src/components/summarizer.js
Labels: bug

#37 Add input url format checker
  src/components/summarizer.js
Labels: frontend

#23 Updated project README based on the modified idea
  README.md
Labels: documentation

#40 Fix conditional rendering
  src/App.js
  src/components/blog.js
  src/components/summarizer.js
Labels: bug, frontend

#41 Add summary length option
  src/components/summarizer.js
Labels: bug, enhancement, frontend

#43 Summarized the randomly fetched blogs
  src/components/blog.js
Labels: enhancement, frontend

#44 Fix card summarizer bug
  src/components/blog.js
Labels: bug, frontend
